networks: 
  loki:
    driver: bridge

services:
  gerador-log:
    image: fabricioveronez/gerador-log
    volumes: 
    - "./logs/gerador-log:/logs/gerador-log"
    ports:
    - 8080:5000
    networks:
    - loki
  
  promtail:
    image: grafana/promtail
    ports:
    - 9080:9080
    depends_on:
    - loki
    - gerador-log
    volumes:
    - "./promtail/config/config.yaml:/etc/promtail/config.yaml"
    - "/var/log:/logs/syslogs"
    - "./logs/gerador-log:/logs/gerador-log"
    - "./promtail/positions:/position"
    command: 
    - -config.file=/etc/promtail/config.yaml
    networks:
    - loki

  loki:
    image: grafana/loki
    ports: 
    - 3100:3100
    command: 
    - -config.file=/etc/loki/local-config.yaml
    - -print-config-stderr=true
    networks:
    - loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    depends_on:
    - loki
    networks:
    - loki
